# -*- coding: utf-8 -*-
"""Untitled40.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t431MXlxSGV0WIbu-6x0BQo6PenVGyoA
"""

import random
import numpy as np
import pandas as pd

SEED = 42
random.seed(SEED)
np.random.seed(SEED)

ROUNDS = 5
NUM_VEHICLES = 200

vehicles = {}


for i in range(1, NUM_VEHICLES + 1):

    vid = f"V{i}"

    label = random.randint(0,3)

    if label == 0:
        trust = random.uniform(0.7,0.9)
    elif label == 1:
        trust = random.uniform(0.5,0.75)
    elif label == 2:
        trust = random.uniform(0.25,0.55)
    else:
        trust = random.uniform(0.05,0.3)

    vehicles[vid] = {
        "label": label,
        "trust": trust
    }

# RSU class
class RSU:

    def __init__(self,name):
        self.name = name
        self.buffer = []

    def receive_from_vehicle(self,packet):
        self.buffer.append(packet)

    def forward_to_vehicle(self):
        return random.randint(1,5)


rsu1 = RSU("RSU1")
rsu2 = RSU("RSU2")
rsu3 = RSU("RSU3")

vehicle_ids = list(vehicles.keys())

RSU_MAP = {
    rsu1: vehicle_ids[:67],
    rsu2: vehicle_ids[67:134],
    rsu3: vehicle_ids[134:]
}

simulation_data = []

print("\nIoV Simulation Start\n")

for round_num in range(1,ROUNDS+1):

    for rsu,vehicle_list in RSU_MAP.items():

        for vid in vehicle_list:

            label = vehicles[vid]["label"]
            trust = vehicles[vid]["trust"]

            forwarded_messages = rsu.forward_to_vehicle()
            consensus = random.choice([0,1])

            # feature generation
            if label == 0:
                msg_rate = np.random.normal(12,5)
                false_ratio = np.random.normal(0.12,0.07)
                drop = np.random.normal(0.05,0.04)
                delay = np.random.normal(0.4,0.2)

            elif label == 1:
                msg_rate = np.random.normal(18,6)
                false_ratio = np.random.normal(0.28,0.12)
                drop = np.random.normal(0.15,0.06)
                delay = np.random.normal(0.7,0.3)

            elif label == 2:
                msg_rate = np.random.normal(24,7)
                false_ratio = np.random.normal(0.45,0.15)
                drop = np.random.normal(0.30,0.08)
                delay = np.random.normal(1.1,0.4)

            else:
                msg_rate = np.random.normal(30,8)
                false_ratio = np.random.normal(0.65,0.18)
                drop = np.random.normal(0.45,0.10)
                delay = np.random.normal(1.7,0.5)

            # CLIP VALUES
            msg_rate = max(1, msg_rate)
            false_ratio = min(1, abs(false_ratio))
            drop = min(1, abs(drop))
            delay = abs(delay)

            #  NORMALIZATION
            norm_msg = min(msg_rate / 30, 1)
            norm_false = false_ratio
            norm_drop = drop
            norm_delay = min(delay / 2, 1)
            norm_forward = forwarded_messages / 5
            norm_consensus = consensus

            # TRUST USING ALL PARAMETERS
            impact = (
                norm_msg +
                (1 - norm_false) +
                (1 - norm_drop) +
                (1 - norm_delay) +
                norm_forward +
                norm_consensus
            ) / 6

            # update trust smoothly
            trust = (trust + impact) / 2

            trust = max(0, min(1, trust))
            vehicles[vid]["trust"] = trust

            packet = {
                "Round": round_num,
                "Vehicle_ID": vid,
                "RSU": rsu.name,

                "RSU_Forwarded_Messages": forwarded_messages,

                "Message_Rate": msg_rate,
                "False_Message_Ratio": false_ratio,
                "Packet_Drop_Rate": drop,
                "Validation_Delay": delay,

                "Trust_Score": trust,
                "Consensus_Participation": consensus,

                "Label": label
            }

            rsu.receive_from_vehicle(packet)
            simulation_data.append(packet)

df = pd.DataFrame(simulation_data)
df.to_csv("iov_dataset_fixed.csv",index=False)

print("Simulation Complete:",len(df))

df[df["Vehicle_ID"] == "V8"]

import hashlib
import time
import pandas as pd
import random

# Load dataset
df = pd.read_csv("iov_dataset_fixed.csv")

RSUs = ["RSU1", "RSU2", "RSU3"]

DIFFICULTY = 2
blockchain = []

# -----------------------
# Hash Function
# -----------------------
def hash_block(block):
    return hashlib.sha256(str(block).encode()).hexdigest()

# -----------------------
# Proof-of-Work Mining
# -----------------------
def pow_mine(block):
    prefix = "0" * DIFFICULTY
    nonce = 0
    start_time = time.time()

    while True:
        block["nonce"] = nonce
        hash_value = hash_block(block)

        if hash_value.startswith(prefix):
            mining_time = time.time() - start_time
            return hash_value, nonce, mining_time

        nonce += 1

# -----------------------
# PRE-VALIDATION (Majority Voting)
# -----------------------
def pre_validate(block, validators):

    votes = []

    for v in validators:

        # Simple rule-based validation
        if (
            block["false_ratio"] < 0.6 and
            block["drop"] < 0.5 and
            block["delay"] < 2
        ):
            votes.append(1)
        else:
            votes.append(0)

    return sum(votes) > len(votes) // 2

# -----------------------
# POST-VALIDATION
# -----------------------
def post_validate(block, block_hash, prev_hash, validators):

    votes = []

    for v in validators:

        valid_hash = block_hash.startswith("0" * DIFFICULTY)
        correct_link = block["previous_hash"] == prev_hash

        if valid_hash and correct_link:
            votes.append(1)
        else:
            votes.append(0)

    return sum(votes) > len(votes) // 2

# -----------------------
# GENESIS BLOCK
# -----------------------
genesis = {
    "previous_hash": "0",
    "timestamp": time.time(),
    "difficulty_level": DIFFICULTY
}

h, n, t = pow_mine(genesis)

genesis["hash"] = h
genesis["nonce"] = n
genesis["mining_time"] = t
genesis["mined_by"] = "RSU_GENESIS"

blockchain.append(genesis)
prev_hash = h

print("\nBlockchain Start (Hybrid Consensus)\n")

# -----------------------
# MAIN LOOP
# -----------------------
for i, row in df.iterrows():

    proposer = random.choice(RSUs)
    validators = [r for r in RSUs if r != proposer]
    miner = random.choice(RSUs)

    block = {
        "vehicle": row["Vehicle_ID"],
        "round": row["Round"],
        "rsu": row["RSU"],

        "msg_rate": row["Message_Rate"],
        "false_ratio": row["False_Message_Ratio"],
        "drop": row["Packet_Drop_Rate"],
        "delay": row["Validation_Delay"],
        "trust": row["Trust_Score"],

        "proposed_by": proposer,
        "validated_by": validators,

        "difficulty_level": DIFFICULTY,
        "previous_hash": prev_hash,
        "timestamp": time.time()
    }

    # -----------------------
    # STEP 1: PRE-VALIDATION
    # -----------------------
    if not pre_validate(block, validators):
        continue  # Reject block before mining

    # -----------------------
    # STEP 2: MINING (PoW)
    # -----------------------
    block_hash, nonce, mining_time = pow_mine(block)

    block["hash"] = block_hash
    block["nonce"] = nonce
    block["mining_time"] = round(mining_time, 4)
    block["mined_by"] = miner

    # -----------------------
    # STEP 3: POST-VALIDATION
    # -----------------------
    if post_validate(block, block_hash, prev_hash, validators):

        blockchain.append(block)
        prev_hash = block_hash

    else:
        continue  # Reject after mining

# -----------------------
# FINAL OUTPUT
# -----------------------
blockchain_df = pd.DataFrame(blockchain)

print("Total Blocks:", len(blockchain_df))

blockchain_df[blockchain_df["vehicle"] == "V1"]

blockchain_df.head(1)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression


# ----------------------------------------
# Load Dataset
# ----------------------------------------

df = pd.read_csv("iov_dataset_fixed.csv")

print("Dataset Shape:", df.shape)

# ----------------------------------------
# Data Preprocessing
# ----------------------------------------

df = df.dropna()
df = df.drop_duplicates()

# Encode RSU column
le = LabelEncoder()
df["RSU"] = le.fit_transform(df["RSU"])

# ----------------------------------------
# Feature Selection
# ----------------------------------------

features = [


"Message_Rate",
"False_Message_Ratio",
"Packet_Drop_Rate",
"Validation_Delay",
"Trust_Score",
"Consensus_Participation",
"RSU"

]

X = df[features]
y = df["Label"]

# ----------------------------------------
# Train Test Split
# ----------------------------------------

X_train, X_test, y_train, y_test = train_test_split(

X,
y,
test_size=0.2,
random_state=42,
stratify=y
)

# ----------------------------------------
# Feature Scaling
# ----------------------------------------

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# ----------------------------------------
# Random Forest
# ----------------------------------------

rf = RandomForestClassifier(

n_estimators=600,
max_depth=20,
random_state=42
)

rf.fit(X_train, y_train)

rf_pred = rf.predict(X_test)

# ----------------------------------------
# SVM
# ----------------------------------------

svm = SVC(

kernel="rbf",
C=0.9
)

svm.fit(X_train, y_train)

svm_pred = svm.predict(X_test)

# ----------------------------------------
# Logistic Regression
# ----------------------------------------

lr = LogisticRegression(

max_iter=2000,
C=0.6
)

lr.fit(X_train, y_train)

lr_pred = lr.predict(X_test)

# ----------------------------------------
# Evaluation Function
# ----------------------------------------

def evaluate(name, pred):

    acc = accuracy_score(y_test, pred)
    prec = precision_score(y_test, pred, average="weighted")
    rec = recall_score(y_test, pred, average="weighted")
    f1 = f1_score(y_test, pred, average="weighted")

    print("\n", name)
    print("Accuracy :", round(acc,3))
    print("Precision:", round(prec,3))
    print("Recall   :", round(rec,3))
    print("F1 Score :", round(f1,3))

    return acc

rf_acc = evaluate("Random Forest", rf_pred)
svm_acc = evaluate("SVM", svm_pred)
lr_acc = evaluate("Logistic Regression", lr_pred)

# ----------------------------------------
# Graph 1 — Accuracy Comparison
# ----------------------------------------

models = ["Random Forest","SVM","Logistic"]

scores = [rf_acc, svm_acc, lr_acc]

plt.bar(models, scores)

plt.title("Model Accuracy Comparison")
plt.ylabel("Accuracy")

plt.show()

# ----------------------------------------
# Graph 2 — Confusion Matrix (Multiclass)
# ----------------------------------------

cm = confusion_matrix(y_test, rf_pred)

sns.heatmap(cm, annot=True, cmap="Blues")

plt.title("Random Forest Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.show()

# ----------------------------------------
# Graph 3 — Feature Importance
# ----------------------------------------

importance = rf.feature_importances_

plt.barh(features, importance)

plt.title("Feature Importance (Random Forest)")

plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Get unique vehicle labels
vehicle_labels = df.drop_duplicates("Vehicle_ID")[["Vehicle_ID","Label"]]

# Convert numeric labels to names
label_map = {
0:"Normal",
1:"Suspicious",
2:"Malicious",
3:"Critical"
}

vehicle_labels["Type"] = vehicle_labels["Label"].map(label_map)

# Plot
plt.figure(figsize=(10,6))

sns.countplot(data=vehicle_labels, x="Type", palette="viridis")

plt.title("Attack Distribution Across Vehicles")

plt.xlabel("Vehicle Behavior Type")

plt.ylabel("Number of Vehicles")

plt.show()

label_map = {
0:"Normal",
1:"Suspicious",
2:"Malicious",
3:"Critical"
}

vehicle_labels = df.drop_duplicates("Vehicle_ID")[["Vehicle_ID","Label"]]

vehicle_labels["Type"] = vehicle_labels["Label"].map(label_map)

vehicle_labels.sort_values("Vehicle_ID")

df[df["Label"] == 3]["Vehicle_ID"].unique()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(7,5))

sns.countplot(x=blockchain_df["mined_by"])

plt.title("RSU Mining Contribution")

plt.xlabel("RSU Miner")

plt.ylabel("Number of Blocks Mined")

plt.show()

import matplotlib.pyplot as plt

vehicles = ["V2", "V1", "V3", "V8"]

plt.figure(figsize=(9,5))

for vid in vehicles:

    temp = df[df["Vehicle_ID"] == vid]

    label = temp["Label"].iloc[0]

    plt.plot(
        temp["Round"],
        temp["Packet_Drop_Rate"],
        marker='o',
        linewidth=2,
        label=f"{vid} (L{label})"
    )

plt.title("Packet Drop Rate Evolution Across Simulation Rounds")
plt.xlabel("Simulation Round")
plt.ylabel("Packet Drop Rate")
plt.legend(title="Vehicle (Label)")
plt.grid(True, linestyle="--", alpha=0.6)

plt.tight_layout()
plt.show()
vehicles = ["V2", "V1", "V3", "V8"]

for vid in vehicles:

    temp = df[df["Vehicle_ID"] == vid]

    print(f"\nVehicle: {vid}")

    # Get label (same for all rows of that vehicle)
    label = temp["Label"].iloc[0]
    print("Label:", label)

    print("Round vs Packet Drop Rate:")

    for _, row in temp.iterrows():
        print(f"Round {int(row['Round'])} → Drop: {round(row['Packet_Drop_Rate'],3)}")

import matplotlib.pyplot as plt
import seaborn as sns

# Map numeric labels to class names
label_map = {
    0: "Normal",
    1: "Suspicious",
    2: "Malicious",
    3: "Critical"
}

df["Class_Type"] = df["Label"].map(label_map)

plt.figure(figsize=(8,5))

sns.boxplot(
    data=df,
    x="Class_Type",
    y="Packet_Drop_Rate"
)

plt.title(" Packet_Drop_Rate vs Vehicle Behavior Class")

plt.xlabel("Vehicle Class")

plt.ylabel("Packet_Drop_Rate")

plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

vehicles = ["V1", "V2", "V3", "V8"]
df_subset = df[df["Vehicle_ID"].isin(vehicles)]

plt.figure(figsize=(8,5))

sns.scatterplot(
    data=df_subset,
    x="Packet_Drop_Rate",
    y="Trust_Score",
    hue="Vehicle_ID",
    s=80
)

sns.regplot(
    data=df_subset,
    x="Packet_Drop_Rate",
    y="Trust_Score",
    scatter=False,
    color="black",
    line_kws={"linewidth":2}
)

plt.title("Drop Rate vs Trust Score (Selected Vehicles)")
plt.xlabel("Packet Drop Rate")
plt.ylabel("Trust Score")

plt.grid(True)
plt.show()